{% set version = "4.1-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lsd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/LSD_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/LSD/LSD_{{ version }}.tar.gz
  sha256: 7553ce29985045849479f2a193cb95bda8172c9d515641e8d9c37db8186deb9e

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('LSD')"           # [not win]
    - "\"%R%\" -e \"library('LSD')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=LSD
  license: GPL-2.0-only OR GPL-3.0-only
  summary: Create lots of colorful plots in a plethora of variations. Try the LSD demotour().
  license_family: OTHER

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r

# Package: LSD
# Version: 4.0-0
# Date: 2018-01-25
# Title: Lots of Superior Depictions
# Author: Bjoern Schwalb [aut, cre], Achim Tresch [aut], Phillipp Torkler [ctb], Sebastian Duemcke [ctb], Carina Demel [ctb], Brian Ripley [ctb], Bill Venables [ctb]
# Maintainer: Bjoern Schwalb <schwalb.bjoern@gmail.com>
# Description: Create lots of colorful plots in a plethora of variations. Try the LSD demotour().
# License: Unlimited
# Packaged: 2018-01-26 16:55:13 UTC; bschwal
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-01-26 17:08:11 UTC
