# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hjLuZ/nQ2p9dUnmqhi+FVWqQYmcog03LuCWDWQWADoiAENAdKIqrkqxjfEAAmZ1eaK98jDv9SKg0Rl4YAdE/XSqT0lZzYaI+DONkglux1/02Q1q00kI6D/6N3gucSPZASsiPDSBFrAUuLJs4GXs7EVnBP8X8udF8RskNb4oUr9jOtyXhgOm0Gc5kVjl/06B6uhMHhYhh5VZW1+RNkCnSQuHa4qJ3hLNLMLjc6QJ83OhnsZk6zKViOxEKkgHzqKL4zDlJyD2vZLmpzYQCgeLSEvumz/YfzK9kupkLU2LIGHSPV/3Ujohpn2Jpn67wsVuDx2lzWdU3aNF5EN/1Ya1i9vrxwEZ8kyMI8z+vtr9/hm5+zMfG13RywMsHIfxUv/qPrQo6Kezg8eBlV76ghUhrrzvEbwYIrh+hytS2oV7vKa/IKfcBz6D5ofdgT63vvTTXGjnfjRhgR5x1mBOSNlHAvULS3RMqVsNx7Z7X6J+yhmpkoaGAfcaH2Ub2Z1srl0565S3NJ2EAgZN2B/qaNFg2ok3zmR25dmxRU03f4cIKXiccxBQZbD+mRlP49dHEuNRq9dQVK/pMuFcmU5vvVocF0BhECYzeAbusvfmxqwTBteBERJ2hUdy3mOGaNUvXaTCZwdcE413aKKKLOKIPivSVYU7eMrAyXcR2t8UWCQSxNzI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
