travis:
  secure:
    BINSTAR_TOKEN: hjLuZ/nQ2p9dUnmqhi+FVWqQYmcog03LuCWDWQWADoiAENAdKIqrkqxjfEAAmZ1eaK98jDv9SKg0Rl4YAdE/XSqT0lZzYaI+DONkglux1/02Q1q00kI6D/6N3gucSPZASsiPDSBFrAUuLJs4GXs7EVnBP8X8udF8RskNb4oUr9jOtyXhgOm0Gc5kVjl/06B6uhMHhYhh5VZW1+RNkCnSQuHa4qJ3hLNLMLjc6QJ83OhnsZk6zKViOxEKkgHzqKL4zDlJyD2vZLmpzYQCgeLSEvumz/YfzK9kupkLU2LIGHSPV/3Ujohpn2Jpn67wsVuDx2lzWdU3aNF5EN/1Ya1i9vrxwEZ8kyMI8z+vtr9/hm5+zMfG13RywMsHIfxUv/qPrQo6Kezg8eBlV76ghUhrrzvEbwYIrh+hytS2oV7vKa/IKfcBz6D5ofdgT63vvTTXGjnfjRhgR5x1mBOSNlHAvULS3RMqVsNx7Z7X6J+yhmpkoaGAfcaH2Ub2Z1srl0565S3NJ2EAgZN2B/qaNFg2ok3zmR25dmxRU03f4cIKXiccxBQZbD+mRlP49dHEuNRq9dQVK/pMuFcmU5vvVocF0BhECYzeAbusvfmxqwTBteBERJ2hUdy3mOGaNUvXaTCZwdcE413aKKKLOKIPivSVYU7eMrAyXcR2t8UWCQSxNzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
