travis:
  secure:
    BINSTAR_TOKEN: UYefFzMIO5GacVZD2NqoRxP5hgt0u+BS3uhMS/cnWY2Tcg+UasYk4aI0sFQbLxHQ+Q4sgR98SPgp4gRjb7ySnwAri6JkF0szWVHBACI6iIhUX4HAKWHvnH/WYaMQAP8YAKaEEL7cQ+avnXcL79htW8RNZbbxLEs++8++WeuoIm2XFPgFF1UX12B+ALCGI5l00y9R4NxRGwPZXhJds/PSO/H4oVUnfiUiQVDU3ZvF64GL0xNzjLV6pTAmSwtMGz4gxKNH6D48ehuTVXBi4Bk1DAK0SWnpIM6JhHRpqKT8Dg5bkFZOWoU9EaqKLnV2raEKjmD0auXDffbuUdk9GERvjBK2j4r1hSzwgaigTJADhipo/XqFEC6GZngoNHzNuUk0TNLI0ixLQlw9KdnjyZNTUixtOzp12E2a+AX38LLYOkJ6kHsFyzZrUKHajYbDEkLd8ta5j9CrViP+oNC5M56oapxI+g+arM3oN6Y+u7zTMpaAUQywo6946CMpj+ZvPKA1MxuxfBQPZlbt2rm20FANntzGf878dFjII2ujt5v+E1iDti+FYF/l9P/onmugr2iqdDglU1r+MylPEIxCXgQdNB7HaD8c+P7WVPcLCMKm+wM2wUhhStObFim80deHjVZTcue7kfw4rzM3Lhe6w7cC2CPKHQxPkwNH8NcqiheuNVA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
